import Image from "next/image";
import Head from "next/head";
export default function About () {
    return (
        <>
        <Head>
        <title>About</title>
        <meta name="About" content="Generated by create next app" />
        <meta name="keywords" content="HTML, CSS, JavaScript" />
      <meta name="author" content="John Doe" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
       <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>About</h1>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Numquam error sed enim quidem tempore eum.</p>
        </>
    )
}