import Head from "next/head";
import Image from "next/image";
import s from "../styles/Home.module.css";
import image from "../public/images/IMG_6083.jpg"

export default function Home() {
  return (
    <div className='content'>
      <Head>
        <title>The Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>
        <h1 className={s.title}>Hello World!</h1>
        <p className={s.font}>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Porro, vel suscipit, debitis nihil sed veritatis, reprehenderit maxime voluptate id ut soluta amet quidem eum repudiandae ad necessitatibus atque tempora veniam officia. Ullam quisquam autem eum, quaerat, corrupti minima quibusdam at quasi rem ipsam animi debitis labore quod assumenda aut nisi.</p>
      </main>
      <a className={s.btn}>Entering a new world</a>
      <Image src={image} alt="flowers" width={100} height={100}/>
    </div>
  );
}
